[package]
name = "alfredworkflow-crontab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powerpack = "0.4.2"
cron = "0.12.0"
chrono = "0.4.23"